--------------------------------------------------------
-- Archivo creado  - miércoles-enero-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence TABLE1_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."TABLE1_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ESPACIO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ESPACIO" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(300 BYTE), 
	"LATITUD" VARCHAR2(100 BYTE), 
	"LONGITUD" VARCHAR2(100 BYTE), 
	"IDLUGARBASEESPOL" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVITACION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."INVITACION" 
   (	"IDINVITACION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDREUNION" NUMBER, 
	"ESTADO" VARCHAR2(2 BYTE) DEFAULT 'E', 
	"IDPERSONA" NUMBER, 
	"CANCELADA" VARCHAR2(2 BYTE) DEFAULT 'F'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTA_PERSONA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."LISTA_PERSONA" 
   (	"IDLISTAPERSONA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDLISTA" NUMBER, 
	"IDPERSONA" NUMBER, 
	"NOMBREPERSONA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTA_PERSONALIZADA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."LISTA_PERSONALIZADA" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDPERSONA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOMBRE_ESPACIO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."NOMBRE_ESPACIO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ESPACIOID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REUNION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."REUNION" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASUNTO" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"IDCREADOR" NUMBER(*,0), 
	"CANCELADA" VARCHAR2(1 BYTE) DEFAULT 'F', 
	"IDLUGAR" NUMBER(*,0), 
	"IDPERIODO" NUMBER(*,0), 
	"FECHAINICIO" TIMESTAMP (6), 
	"FECHAFIN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ADMIN"."REUNION"."IDLUGAR" IS 'Es el id del lugar en base espol.';
--------------------------------------------------------
--  DDL for Index ESPACIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."ESPACIO_PK" ON "ADMIN"."ESPACIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INVITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."INVITACION_PK" ON "ADMIN"."INVITACION" ("IDINVITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LISTA_PERSONALIZADA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."LISTA_PERSONALIZADA_PK" ON "ADMIN"."LISTA_PERSONALIZADA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LISTA_PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."LISTA_PERSONA_PK" ON "ADMIN"."LISTA_PERSONA" ("IDLISTAPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOMBRE_ESPACIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."NOMBRE_ESPACIO_PK" ON "ADMIN"."NOMBRE_ESPACIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REUNION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."REUNION_PK" ON "ADMIN"."REUNION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure BLOQUE_ADD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."BLOQUE_ADD" 
(
  DESCRIPCION IN VARCHAR2 
, LATITUD IN VARCHAR2 
, LONGITUD IN VARCHAR2 
, RESULT_ID OUT NUMBER 
) AS 
BEGIN
  INSERT INTO admin.BLOQUE
  (DESCRIPCION,LATITUD,LONGITUD)
  VALUES
  (DESCRIPCION,LATITUD,LONGITUD)
  RETURNING ID INTO RESULT_ID;
END BLOQUE_ADD;

/
--------------------------------------------------------
--  DDL for Procedure BLOQUE_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."BLOQUE_ITEM_ID" (
    BLOQUE_ID IN NUMBER,
    BLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN BLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion,
        'latitud' VALUE latitud,
        'longitud' VALUE longitud
    ) FROM ADMIN.BLOQUE
    WHERE id = BLOQUE_ID;
END BLOQUE_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure BLOQUE_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."BLOQUE_LIST" (
    BLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN BLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion
    ) FROM ADMIN.BLOQUE;
END BLOQUE_LIST;

/
--------------------------------------------------------
--  DDL for Procedure ESPACIO_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."ESPACIO_ITEM_ID" (
    ESPACIO_ID IN NUMBER,
    ESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion,
        'bloque' VALUE bloque,
        'latitud' VALUE latitud,
        'longitud' VALUE longitud
    ) FROM ADMIN.ESPACIO
    WHERE id = ESPACIO_ID;
END ESPACIO_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure ESPACIO_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."ESPACIO_LIST" (
    ESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion,
        'bloque' VALUE bloque
    ) FROM ADMIN.ESPACIO;
END ESPACIO_LIST;

/
--------------------------------------------------------
--  DDL for Procedure ESTADO_INVITACION_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."ESTADO_INVITACION_ITEM_ID" (
    ESTADO_INVITACION_ID IN NUMBER,
    ESTADOINVITACIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESTADOINVITACIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'abreviatura' VALUE abreviatura
    ) FROM ADMIN.ESTADO_INVITACION
    WHERE id = ESTADO_INVITACION_ID;
END ESTADO_INVITACION_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure ESTADO_INVITACION_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."ESTADO_INVITACION_LIST" (
    ESTADOINVITACIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESTADOINVITACIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'abreviatura' VALUE abreviatura
    ) FROM ADMIN.ESTADO_INVITACION;
END ESTADO_INVITACION_LIST;

/
--------------------------------------------------------
--  DDL for Procedure LISTA_PERSONALIZADA_ADD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."LISTA_PERSONALIZADA_ADD" 
(
  IDPERSONA IN NUMBER
, NOMBRE IN VARCHAR2 
, RESULT_ID OUT NUMBER 
) AS 
BEGIN
  INSERT INTO admin.lista_personalizada
  (IDPERSONA,NOMBRE)
  VALUES
  (IDPERSONA,NOMBRE)
  RETURNING ID INTO RESULT_ID;
END LISTA_PERSONALIZADA_ADD;

/
--------------------------------------------------------
--  DDL for Procedure LISTA_PERSONALIZADA_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."LISTA_PERSONALIZADA_ITEM_ID" (
    LISTA_PERSONALIZADA_ID IN NUMBER,
    LISTAPERSONALIZADACURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN LISTAPERSONALIZADACURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'idpersona' VALUE idpersona,
        'nombre' VALUE nombre
    ) FROM ADMIN.LISTA_PERSONALIZADA
    WHERE id = LISTA_PERSONALIZADA_ID;
END LISTA_PERSONALIZADA_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure LISTA_PERSONALIZADA_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."LISTA_PERSONALIZADA_LIST" (
    LISTAPERSONALIZADACURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN LISTAPERSONALIZADACURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'idpersona' VALUE idpersona,
        'nombre' VALUE nombre
    ) FROM ADMIN.LISTA_PERSONALIZADA;
END LISTA_PERSONALIZADA_LIST;

/
--------------------------------------------------------
--  DDL for Procedure NOMBRE_BLOQUE_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."NOMBRE_BLOQUE_ITEM_ID" (
    NOMBRE_BLOQUE_ID IN NUMBER,
    NOMBREBLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREBLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'bloque' Value bloque
    ) FROM ADMIN.NOMBRE_BLOQUE
    WHERE id = NOMBRE_BLOQUE_ID;
END NOMBRE_BLOQUE_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure NOMBRE_BLOQUE_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."NOMBRE_BLOQUE_LIST" (
    NOMBREBLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREBLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'bloque' VALUE bloque
    ) FROM ADMIN.NOMBRE_BLOQUE;
END NOMBRE_BLOQUE_LIST;

/
--------------------------------------------------------
--  DDL for Procedure NOMBRE_ESPACIO_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."NOMBRE_ESPACIO_ITEM_ID" (
    NOMBRE_ESPACIO_ID IN NUMBER,
    NOMBREESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'espacio' VALUE espacioid
    ) FROM ADMIN.NOMBRE_ESPACIO
    WHERE id = NOMBRE_ESPACIO_ID;
END NOMBRE_ESPACIO_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure NOMBRE_ESPACIO_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."NOMBRE_ESPACIO_LIST" (
    NOMBREESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'espacio' VALUE espacioid
    ) FROM ADMIN.NOMBRE_ESPACIO;
END NOMBRE_ESPACIO_LIST;

/
--------------------------------------------------------
--  DDL for Procedure REUNION_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."REUNION_ITEM_ID" (
    REUNION_ID IN NUMBER,
    REUNIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN REUNIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'usernameorganizador' VALUE usernameorganizador,
        'eliminado' VALUE eliminado
    ) FROM ADMIN.REUNION
    WHERE id = REUNION_ID;
END REUNION_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure REUNION_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."REUNION_LIST" (
    REUNIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN REUNIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'usernameorganizador' VALUE usernameorganizador,
        'eliminado' VALUE eliminado
    ) FROM ADMIN.REUNION;
END REUNION_LIST;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_ESPACIO_ADD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."TIPO_ESPACIO_ADD" 
(
  NOMBRE IN VARCHAR2 
, RETURN_ID OUT NUMBER 
) AS 
BEGIN
  INSERT INTO admin.TIPO_ESPACIO
  (NOMBRE)
  VALUES
  (NOMBRE)
  RETURNING ID INTO RETURN_ID;
END TIPO_ESPACIO_ADD;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_ESPACIO_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."TIPO_ESPACIO_ITEM_ID" (
    ESPACIO_ID IN NUMBER,
    TIPOESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre
    ) FROM ADMIN.TIPO_ESPACIO
    WHERE id = ESPACIO_ID;
END TIPO_ESPACIO_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_ESPACIO_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."TIPO_ESPACIO_LIST" (
    TIPOESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre
    ) FROM ADMIN.TIPO_ESPACIO;
END TIPO_ESPACIO_LIST;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_FILTRO_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."TIPO_FILTRO_ITEM_ID" (
    FILTRO_ID IN NUMBER,
    TIPOFILTROCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOFILTROCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'criterio' VALUE criterio
    ) FROM ADMIN.TIPO_FILTRO
    WHERE id = FILTRO_ID;
END TIPO_FILTRO_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_FILTRO_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN"."TIPO_FILTRO_LIST" (
    TIPOFILTROCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOFILTROCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'criterio' VALUE criterio
    ) FROM ADMIN.TIPO_FILTRO;
END TIPO_FILTRO_LIST;

/
--------------------------------------------------------
--  Constraints for Table LISTA_PERSONALIZADA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."LISTA_PERSONALIZADA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LISTA_PERSONALIZADA" MODIFY ("IDPERSONA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LISTA_PERSONALIZADA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LISTA_PERSONALIZADA" ADD CONSTRAINT "LISTA_PERSONALIZADA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LISTA_PERSONA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."LISTA_PERSONA" MODIFY ("IDLISTAPERSONA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LISTA_PERSONA" ADD CONSTRAINT "LISTA_PERSONA_PK" PRIMARY KEY ("IDLISTAPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOMBRE_ESPACIO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."NOMBRE_ESPACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."NOMBRE_ESPACIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."NOMBRE_ESPACIO" MODIFY ("ESPACIOID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."NOMBRE_ESPACIO" ADD CONSTRAINT "NOMBRE_ESPACIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESPACIO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ESPACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ESPACIO" ADD CONSTRAINT "ESPACIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REUNION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."REUNION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."REUNION" ADD CONSTRAINT "REUNION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."REUNION" MODIFY ("IDCREADOR" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."REUNION" MODIFY ("ASUNTO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."REUNION" MODIFY ("IDLUGAR" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."REUNION" MODIFY ("CANCELADA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVITACION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."INVITACION" MODIFY ("IDINVITACION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INVITACION" MODIFY ("IDREUNION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INVITACION" MODIFY ("IDPERSONA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INVITACION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INVITACION" MODIFY ("CANCELADA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INVITACION" ADD CONSTRAINT "INVITACION_PK" PRIMARY KEY ("IDINVITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOMBRE_ESPACIO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."NOMBRE_ESPACIO" ADD CONSTRAINT "NOMBRE_ESPACIO_FK1" FOREIGN KEY ("ESPACIOID")
	  REFERENCES "ADMIN"."ESPACIO" ("ID") ENABLE;
