--------------------------------------------------------
-- Archivo creado  - sábado-febrero-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence TABLE1_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."TABLE1_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ESPACIO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESPACIO" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(300 BYTE), 
	"LATITUD" VARCHAR2(100 BYTE), 
	"LONGITUD" VARCHAR2(100 BYTE), 
	"IDLUGARBASEESPOL" NUMBER, 
	"TIPO" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"SUCESOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVITACION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."INVITACION" 
   (	"IDINVITACION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDREUNION" NUMBER, 
	"ESTADO" VARCHAR2(2 BYTE) DEFAULT 'E', 
	"IDPERSONA" NUMBER, 
	"CANCELADA" VARCHAR2(2 BYTE) DEFAULT 'F', 
	"NOMBREPERSONA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTA_PERSONA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LISTA_PERSONA" 
   (	"IDLISTAPERSONA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDLISTA" NUMBER, 
	"IDPERSONA" NUMBER, 
	"NOMBREPERSONA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTA_PERSONALIZADA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LISTA_PERSONALIZADA" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDPERSONA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOMBRE_ESPACIO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."NOMBRE_ESPACIO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ESPACIOID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REUNION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REUNION" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASUNTO" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"IDCREADOR" NUMBER(*,0), 
	"CANCELADA" VARCHAR2(1 BYTE) DEFAULT 'F', 
	"IDLUGAR" NUMBER(*,0), 
	"IDPERIODO" NUMBER(*,0), 
	"FECHAINICIO" TIMESTAMP (6), 
	"FECHAFIN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SYSTEM"."REUNION"."IDLUGAR" IS 'Es el id del lugar en base espol.';
REM INSERTING into SYSTEM.ESPACIO
SET DEFINE OFF;
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3A ','-2.15194979424615','-79.9568356196129','1180','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3B ','-2.15168350029237','-79.9570592639783','1172','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3C ','-2.15109424908609','-79.9574196363659',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3D ','-2.15080391106658','-79.957740085402','1173','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3E ','-2.15061597982927','-79.957287222491','1174','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3F','-2.15127801575397','-79.9566446982274',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3G','-2.15157554138476','-79.9556754455409',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3H','-2.15247968546254','-79.9556330097391','1175','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3I','-2.15139942897428','-79.9548829814701','1176','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3J','-2.15112390807286','-79.9549886200083',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3K','-2.15142940002216','-79.9543605866625','1177','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3L','-2.15171003669288','-79.9541193124823','1178','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('3M','-2.15211903360149','-79.9540452015248','1179','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5A','-2.14708835225555','-79.9627848917901','1181','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5B','-2.1468860208484','-79.96268422',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5C','-2.147165032037','-79.96212409',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5D','-2.14700969906781','-79.96205878',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5E','-2.146723669','-79.96211629','1182','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5F','-2.146514281','-79.96221878','1183','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5G','-2.14666563','-79.96237702','1184','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5H','-2.14674283','-79.96274028','1185','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5I','-2.146729741','-79.96289762','1186','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5J','-2.146684539','-79.96306438',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('5K','-2.146962488','-79.96317497','1187','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('6A','-2.147756365','-79.96449935','1188','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('6B','-2.147987797','-79.96373853',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('7A','-2.14350894','-77.27060043','1189','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('7B','-2.147407321','-79.96601998','1190','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('7C','-2.147287117','-79.96526725',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8A','-2.147898097','-79.96862787',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8B','-2.148435431','-79.96857589','1192','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8C','-2.148494777','-79.96801761',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8D','-2.14867464','-79.96778206',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8E','-2.148886602','-79.9352252','1193','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8F','-2.148990029','-79.96732885','1194','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8G','-2.148796715','-79.96709706','1195','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8H','-2.148598548','-79.96730093','1196','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8J','-2.148804647','-79.96739817',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('8K','-2.148929158','-79.96484393','1197','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9A','-2.147006236','-79.9669849',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9B','-2.146804901','-79.96701113','1198','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9C','-2.147490174','-79.96684906','1199','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9D','-2.147666955','-79.96713415',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9E','-2.147789289','-79.96769262','1200','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9F','-2.147419799','-79.9674815','1201','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9G','-2.147014124','-79.96770166','1202','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9H','-2.14680949','-79.96765353','1203','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9I','-2.146344012','-79.96694343','1204','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9J','-2.14628868','-79.96665147',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9K','-2.146574281','-79.96687338',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9L','-2.14680247','-79.96701034','1205','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('9M','-2.147011921','-79.96663385','1206','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('10A','-2.14308562','-79.96683688',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('10B','-2.143391219','-79.96563934','1207','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('10AD1','-2.143746692','-79.96770567',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('10AD2','-2.142718555','-79.96736574',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('10AD3','-2.142150427','-79.96688651',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('4A','-2.153830064','-79.95675638',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('4AD1','-2.153573716','-79.95845856',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('4B','-2.152265744','-79.96021658',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('11A','-2.144767931','-79.9674734','1208','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('11B','-2.140997285','-77.27150593','1209','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('11C','-2.145754906','-79.96671177','1210','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('11D','-2.14561668','-79.96583371','1211','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('11E','-2.14522037','-79.96603541',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('11F','-2.14519278','-79.9662842','1212','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12A','-2.144673929','-79.96579213','1213','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12B','-2.144907381','-79.96539297',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12C','-2.145140041','-79.96558158','1214','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12D','-2.144973052','-79.96593102',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12E','-2.144823116','-79.96615342','1215','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12F','-2.144743067','-79.96637464','1216','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12G','-2.144610039','-79.9661889','1217','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12H','-2.144349978','-79.96620589','1218','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12I','-2.144217074','-79.96578809','1219','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12J','-2.14429942','-79.96596776','1220','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12K','-2.144182188','-79.96631266','1221','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12L','-2.143816126','-79.96592167','1222','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12M','-2.144168701','-79.96676419',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('12N','-2.144025803','-79.96696279','1223','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13A','-2.14564468','-79.9651237','1829','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13B','-2.145713528','-79.9648738','1791','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13C','-2.145306059','-79.96479955','1790','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13D','-2.145649117','-79.96472628','1792','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13E','-2.145911176','-79.9647019','1793','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13F','-2.146111413','-79.96499961','1794','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13G','-2.146083912','-79.96528147','1795','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13H','-2.146062725','-79.96553972','1224','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13I','-2.146128837','-79.96609019','1225','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13J','-2.146299979','-79.96538131',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13K','-2.14664561','-79.96484121',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13L','-2.146393795','-79.96488841',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13M','-2.146556666','-79.96448821','1227','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('13N','-2.146366684','-79.9641173','1228','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('14A','-2.144208259','-79.96226242','1229','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('14B','-2.143771302','-79.96209569','1230','E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('14C','-2.143800302','-79.9612671',null,'E','V',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 37','-2.15194979424615','-79.9568356196129','401','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 45','-2.15080391106658','-79.957740085402','33','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 42','-2.15061598','-79.95728722','32','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 55 MANTENIMIENTO','-2.15127802','-79.95664470','1032','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 41','-2.15247969','-79.95563301','31','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 47','-2.15142940','-79.95436059','34','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 34','-2.15171004','-79.95411931','30','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 33','-2.15211903','-79.95404520','29','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE DEPORTE',null,null,'929','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 60','-2.14708835','-79.96278489','417','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 63A/FMAR','-2.14700970','-79.96205878','418','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 63B/FMAR','-2.14716503','-79.96212409','419','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 62','-2.14672974','-79.96289762','421','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 61/FMAR','-2.14696249','-79.96317497','420','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 2A CEPROEM','-2.14740732','-79.96601998','977','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 21 FCSH','-2.14789810','-79.96862787','978','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 32E','-2.14843543','-79.96857589','28','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 31A','-2.14859855','-79.96730093','660','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 31B','-2.14879672','-79.96709706','661','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 31C','-2.14899003','-79.96732885','662','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 31D','-2.14880465','-79.96739817','663','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 31E','-2.14888660','-79.93522520','771','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 32B','-2.14680490','-79.96701113','25','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 26A','-2.14778929','-79.96769262','1003','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 32C','-2.14741980','-79.96748150','26','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 27A','-2.14701412','-79.96770166','23','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 27B','-2.14680949','-79.96765353','23','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 32D','-2.14634401','-79.96694343','27','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 25','-2.14657428','-79.96687338','452','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 32A','-2.14701192','-79.96663385','24','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('GIMNASIO ESTUDIANTES',null,null,'954','A','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 57 LEMAT-FIMCP','-2.14339122','-79.96563934','1000','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 15A','-2.14476793','-79.96747340','398','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 16C','-2.14099729','-77.27150593','400','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 16A','-2.14575491','-79.96671177','1105','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 24A','-2.14561668','-79.96583371','399','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 17 FIMCP','-2.14467393','-79.96579213','998','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 24C FIMCP','-2.14514004','-79.96558158','22','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 18B FIMCP','-2.14482312','-79.96615342','13','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 18E FIMCP','-2.14474307','-79.96637464','1081','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 18C FIMCP','-2.14482312','-79.96615342','14','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 24E FIMCP','-2.14434998','-79.96620589','558','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 18A FIMCP','-2.14421707','-79.96578809','12','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 18D FIMCP','-2.14418219','-79.96631266','999','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('STEM 90','-2.14381613','-79.96592167','1103','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 20A- FICT','-2.14571353','-79.96487380','16','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 20B- FICT','-2.14564912','-79.96472628','17','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 20C- FICT','-2.14591118','-79.96470190','18','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 20D- FICT','-2.14611141','-79.96499961','19','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE 19A- FICT','-2.14606273','-79.96553972','15','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('BLOQUE EDCOM','-2.14420826','-79.96226242','685','E','N',null);
Insert into SYSTEM.ESPACIO (DESCRIPCION,LATITUD,LONGITUD,IDLUGARBASEESPOL,TIPO,ESTADO,SUCESOR) values ('AULAS EDCOM','-2.14377130','-79.96209569','839','E','N',null);

--------------------------------------------------------
--  DDL for Index ESPACIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ESPACIO_PK" ON "SYSTEM"."ESPACIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INVITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."INVITACION_PK" ON "SYSTEM"."INVITACION" ("IDINVITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LISTA_PERSONALIZADA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LISTA_PERSONALIZADA_PK" ON "SYSTEM"."LISTA_PERSONALIZADA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LISTA_PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LISTA_PERSONA_PK" ON "SYSTEM"."LISTA_PERSONA" ("IDLISTAPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOMBRE_ESPACIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."NOMBRE_ESPACIO_PK" ON "SYSTEM"."NOMBRE_ESPACIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REUNION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."REUNION_PK" ON "SYSTEM"."REUNION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure BLOQUE_ADD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."BLOQUE_ADD" 
(
  DESCRIPCION IN VARCHAR2 
, LATITUD IN VARCHAR2 
, LONGITUD IN VARCHAR2 
, RESULT_ID OUT NUMBER 
) AS 
BEGIN
  INSERT INTO SYSTEM.BLOQUE
  (DESCRIPCION,LATITUD,LONGITUD)
  VALUES
  (DESCRIPCION,LATITUD,LONGITUD)
  RETURNING ID INTO RESULT_ID;
END BLOQUE_ADD;

/
--------------------------------------------------------
--  DDL for Procedure BLOQUE_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."BLOQUE_ITEM_ID" (
    BLOQUE_ID IN NUMBER,
    BLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN BLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion,
        'latitud' VALUE latitud,
        'longitud' VALUE longitud
    ) FROM SYSTEM.BLOQUE
    WHERE id = BLOQUE_ID;
END BLOQUE_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure BLOQUE_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."BLOQUE_LIST" (
    BLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN BLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion
    ) FROM SYSTEM.BLOQUE;
END BLOQUE_LIST;

/
--------------------------------------------------------
--  DDL for Procedure ESPACIO_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."ESPACIO_ITEM_ID" (
    ESPACIO_ID IN NUMBER,
    ESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion,
        'bloque' VALUE bloque,
        'latitud' VALUE latitud,
        'longitud' VALUE longitud
    ) FROM SYSTEM.ESPACIO
    WHERE id = ESPACIO_ID;
END ESPACIO_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure ESPACIO_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."ESPACIO_LIST" (
    ESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion,
        'bloque' VALUE bloque
    ) FROM SYSTEM.ESPACIO;
END ESPACIO_LIST;

/
--------------------------------------------------------
--  DDL for Procedure ESTADO_INVITACION_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."ESTADO_INVITACION_ITEM_ID" (
    ESTADO_INVITACION_ID IN NUMBER,
    ESTADOINVITACIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESTADOINVITACIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'abreviatura' VALUE abreviatura
    ) FROM SYSTEM.ESTADO_INVITACION
    WHERE id = ESTADO_INVITACION_ID;
END ESTADO_INVITACION_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure ESTADO_INVITACION_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."ESTADO_INVITACION_LIST" (
    ESTADOINVITACIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESTADOINVITACIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'abreviatura' VALUE abreviatura
    ) FROM SYSTEM.ESTADO_INVITACION;
END ESTADO_INVITACION_LIST;

/
--------------------------------------------------------
--  DDL for Procedure LISTA_PERSONALIZADA_ADD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."LISTA_PERSONALIZADA_ADD" 
(
  IDPERSONA IN NUMBER
, NOMBRE IN VARCHAR2 
, RESULT_ID OUT NUMBER 
) AS 
BEGIN
  INSERT INTO SYSTEM.lista_personalizada
  (IDPERSONA,NOMBRE)
  VALUES
  (IDPERSONA,NOMBRE)
  RETURNING ID INTO RESULT_ID;
END LISTA_PERSONALIZADA_ADD;

/
--------------------------------------------------------
--  DDL for Procedure LISTA_PERSONALIZADA_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."LISTA_PERSONALIZADA_ITEM_ID" (
    LISTA_PERSONALIZADA_ID IN NUMBER,
    LISTAPERSONALIZADACURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN LISTAPERSONALIZADACURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'idpersona' VALUE idpersona,
        'nombre' VALUE nombre
    ) FROM SYSTEM.LISTA_PERSONALIZADA
    WHERE id = LISTA_PERSONALIZADA_ID;
END LISTA_PERSONALIZADA_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure LISTA_PERSONALIZADA_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."LISTA_PERSONALIZADA_LIST" (
    LISTAPERSONALIZADACURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN LISTAPERSONALIZADACURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'idpersona' VALUE idpersona,
        'nombre' VALUE nombre
    ) FROM SYSTEM.LISTA_PERSONALIZADA;
END LISTA_PERSONALIZADA_LIST;

/
--------------------------------------------------------
--  DDL for Procedure NOMBRE_BLOQUE_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."NOMBRE_BLOQUE_ITEM_ID" (
    NOMBRE_BLOQUE_ID IN NUMBER,
    NOMBREBLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREBLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'bloque' Value bloque
    ) FROM SYSTEM.NOMBRE_BLOQUE
    WHERE id = NOMBRE_BLOQUE_ID;
END NOMBRE_BLOQUE_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure NOMBRE_BLOQUE_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."NOMBRE_BLOQUE_LIST" (
    NOMBREBLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREBLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'bloque' VALUE bloque
    ) FROM SYSTEM.NOMBRE_BLOQUE;
END NOMBRE_BLOQUE_LIST;

/
--------------------------------------------------------
--  DDL for Procedure NOMBRE_ESPACIO_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."NOMBRE_ESPACIO_ITEM_ID" (
    NOMBRE_ESPACIO_ID IN NUMBER,
    NOMBREESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'espacio' VALUE espacioid
    ) FROM SYSTEM.NOMBRE_ESPACIO
    WHERE id = NOMBRE_ESPACIO_ID;
END NOMBRE_ESPACIO_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure NOMBRE_ESPACIO_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."NOMBRE_ESPACIO_LIST" (
    NOMBREESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'espacio' VALUE espacioid
    ) FROM SYSTEM.NOMBRE_ESPACIO;
END NOMBRE_ESPACIO_LIST;

/
--------------------------------------------------------
--  DDL for Procedure REUNION_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."REUNION_ITEM_ID" (
    REUNION_ID IN NUMBER,
    REUNIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN REUNIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'usernameorganizador' VALUE usernameorganizador,
        'eliminado' VALUE eliminado
    ) FROM SYSTEM.REUNION
    WHERE id = REUNION_ID;
END REUNION_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure REUNION_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."REUNION_LIST" (
    REUNIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN REUNIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'usernameorganizador' VALUE usernameorganizador,
        'eliminado' VALUE eliminado
    ) FROM SYSTEM.REUNION;
END REUNION_LIST;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_ESPACIO_ADD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."TIPO_ESPACIO_ADD" 
(
  NOMBRE IN VARCHAR2 
, RETURN_ID OUT NUMBER 
) AS 
BEGIN
  INSERT INTO SYSTEM.TIPO_ESPACIO
  (NOMBRE)
  VALUES
  (NOMBRE)
  RETURNING ID INTO RETURN_ID;
END TIPO_ESPACIO_ADD;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_ESPACIO_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."TIPO_ESPACIO_ITEM_ID" (
    ESPACIO_ID IN NUMBER,
    TIPOESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre
    ) FROM SYSTEM.TIPO_ESPACIO
    WHERE id = ESPACIO_ID;
END TIPO_ESPACIO_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_ESPACIO_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."TIPO_ESPACIO_LIST" (
    TIPOESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre
    ) FROM SYSTEM.TIPO_ESPACIO;
END TIPO_ESPACIO_LIST;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_FILTRO_ITEM_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."TIPO_FILTRO_ITEM_ID" (
    FILTRO_ID IN NUMBER,
    TIPOFILTROCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOFILTROCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'criterio' VALUE criterio
    ) FROM SYSTEM.TIPO_FILTRO
    WHERE id = FILTRO_ID;
END TIPO_FILTRO_ITEM_ID;

/
--------------------------------------------------------
--  DDL for Procedure TIPO_FILTRO_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."TIPO_FILTRO_LIST" (
    TIPOFILTROCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOFILTROCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'criterio' VALUE criterio
    ) FROM SYSTEM.TIPO_FILTRO;
END TIPO_FILTRO_LIST;

/
--------------------------------------------------------
--  Constraints for Table LISTA_PERSONALIZADA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LISTA_PERSONALIZADA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LISTA_PERSONALIZADA" MODIFY ("IDPERSONA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LISTA_PERSONALIZADA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LISTA_PERSONALIZADA" ADD CONSTRAINT "LISTA_PERSONALIZADA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LISTA_PERSONA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LISTA_PERSONA" MODIFY ("IDLISTAPERSONA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LISTA_PERSONA" ADD CONSTRAINT "LISTA_PERSONA_PK" PRIMARY KEY ("IDLISTAPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOMBRE_ESPACIO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NOMBRE_ESPACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NOMBRE_ESPACIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NOMBRE_ESPACIO" MODIFY ("ESPACIOID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NOMBRE_ESPACIO" ADD CONSTRAINT "NOMBRE_ESPACIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESPACIO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESPACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESPACIO" ADD CONSTRAINT "ESPACIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REUNION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REUNION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REUNION" ADD CONSTRAINT "REUNION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SYSTEM"."REUNION" MODIFY ("IDCREADOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REUNION" MODIFY ("ASUNTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REUNION" MODIFY ("IDLUGAR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REUNION" MODIFY ("CANCELADA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVITACION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."INVITACION" MODIFY ("IDINVITACION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."INVITACION" MODIFY ("IDREUNION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."INVITACION" MODIFY ("IDPERSONA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."INVITACION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."INVITACION" MODIFY ("CANCELADA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."INVITACION" ADD CONSTRAINT "INVITACION_PK" PRIMARY KEY ("IDINVITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOMBRE_ESPACIO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NOMBRE_ESPACIO" ADD CONSTRAINT "NOMBRE_ESPACIO_FK1" FOREIGN KEY ("ESPACIOID")
	  REFERENCES "SYSTEM"."ESPACIO" ("ID") ENABLE;
