create or replace NONEDITIONABLE PROCEDURE BLOQUE_LIST (
    BLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN BLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion
    ) FROM ADMIN.BLOQUE;
END BLOQUE_LIST;

create or replace NONEDITIONABLE PROCEDURE BLOQUE_ITEM_ID (
    BLOQUE_ID IN NUMBER,
    BLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN BLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion
    ) FROM ADMIN.BLOQUE
    WHERE id = BLOQUE_ID;
END BLOQUE_ITEM_ID;

create or replace NONEDITIONABLE PROCEDURE ESPACIO_LIST (
    ESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion,
        'bloque' VALUE bloque
    ) FROM ADMIN.ESPACIO;
END ESPACIO_LIST;

create or replace NONEDITIONABLE PROCEDURE ESPACIO_ITEM_ID (
    ESPACIO_ID IN NUMBER,
    ESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'descripcion' VALUE descripcion,
        'bloque' VALUE bloque
    ) FROM ADMIN.ESPACIO
    WHERE id = ESPACIO_ID;
END ESPACIO_ITEM_ID;

create or replace NONEDITIONABLE PROCEDURE ESTADO_INVITACION_LIST (
    ESTADOINVITACIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESTADOINVITACIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'abreviatura' VALUE abreviatura
    ) FROM ADMIN.ESTADO_INVITACION;
END ESTADO_INVITACION_LIST;

create or replace NONEDITIONABLE PROCEDURE ESTADO_INVITACION_ITEM_ID (
    ESTADO_INVITACION_ID IN NUMBER,
    ESTADOINVITACIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN ESTADOINVITACIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'abreviatura' VALUE abreviatura
    ) FROM ADMIN.ESTADO_INVITACION
    WHERE id = ESTADO_INVITACION_ID;
END ESTADO_INVITACION_ITEM_ID;

create or replace NONEDITIONABLE PROCEDURE LISTA_PERSONALIZADA_LIST (
    LISTAPERSONALIZADACURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN LISTAPERSONALIZADACURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'usuario' VALUE usuario,
        'nombre' VALUE nombre,
        'fecha_creacion' VALUE fecha_creacion
    ) FROM ADMIN.ESTADO_INVITACION;
END LISTA_PERSONALIZADA_LIST;

create or replace NONEDITIONABLE PROCEDURE LISTA_PERSONALIZADA_ITEM_ID (
    LISTA_PERSONALIZADA_ID IN NUMBER,
    LISTAPERSONALIZADACURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN LISTAPERSONALIZADACURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'usuario' VALUE usuario,
        'nombre' VALUE nombre,
        'fecha_creacion' VALUE fecha_creacion
    ) FROM ADMIN.LISTA_PERSONALIZADA
    WHERE id = LISTA_PERSONALIZADA_ID;
END LISTA_PERSONALIZADA_ITEM_ID;

create or replace NONEDITIONABLE PROCEDURE NOMBRE_BLOQUE_LIST (
    NOMBREBLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREBLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'bloque' VALUE bloque
    ) FROM ADMIN.NOMBRE_BLOQUE;
END NOMBRE_BLOQUE_LIST;

create or replace NONEDITIONABLE PROCEDURE NOMBRE_BLOQUE_ITEM_ID (
    NOMBRE_BLOQUE_ID IN NUMBER,
    NOMBREBLOQUECURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREBLOQUECURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'bloque' Value bloque,
    ) FROM ADMIN.NOMBRE_BLOQUE
    WHERE id = NOMBRE_BLOQUE_ID;
END NOMBRE_BLOQUE_ITEM_ID;

create or replace NONEDITIONABLE PROCEDURE NOMBRE_ESPACIO_LIST (
    NOMBREESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'espacio' VALUE espacioid
    ) FROM ADMIN.NOMBRE_ESPACIO;
END NOMBRE_ESPACIO_LIST;

create or replace NONEDITIONABLE PROCEDURE NOMBRE_ESPACIO_ITEM_ID (
    NOMBRE_ESPACIO_ID IN NUMBER,
    NOMBREESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN NOMBREESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'nombre' VALUE nombre,
        'espacio' VALUE espacioid,
    ) FROM ADMIN.NOMBRE_ESPACIO
    WHERE id = NOMBRE_ESPACIO_ID;
END NOMBRE_ESPACIO_ITEM_ID;

create or replace NONEDITIONABLE PROCEDURE REUNION_LIST (
    REUNIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN REUNIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'usernameorganizador' VALUE usernameorganizador,
        'eliminado' VALUE eliminado
    ) FROM ADMIN.REUNION;
END REUNION_LIST;

create or replace NONEDITIONABLE PROCEDURE REUNION_ITEM_ID (
    REUNION_ID IN NUMBER,
    REUNIONCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN REUNIONCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'usernameorganizador' VALUE usernameorganizador,
        'eliminado' VALUE eliminado
    ) FROM ADMIN.REUNION
    WHERE id = REUNION_ID;
END REUNION_ITEM_ID;

create or replace NONEDITIONABLE PROCEDURE TIPO_ESPACIO_LIST (
    TIPOESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'criterio' VALUE criterio
    ) FROM ADMIN.TIPO_ESPACIO;
END TIPO_ESPACIO_LIST;

create or replace NONEDITIONABLE PROCEDURE TIPO_ESPACIO_ITEM_ID (
    ESPACIO_ID IN NUMBER,
    TIPOESPACIOCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOESPACIOCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'criterio' VALUE criterio
    ) FROM ADMIN.TIPO_ESPACIO
    WHERE id = ESPACIO_ID;
END TIPO_ESPACIO_ITEM_ID;

create or replace NONEDITIONABLE PROCEDURE TIPO_FILTRO_LIST (
    TIPOFILTROCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOFILTROCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'criterio' VALUE criterio
    ) FROM ADMIN.TIPO_FILTRO;
END TIPO_FILTRO_LIST;

create or replace NONEDITIONABLE PROCEDURE TIPO_FILTRO_ITEM_ID (
    FILTRO_ID IN NUMBER,
    TIPOFILTROCURSOR OUT SYS_REFCURSOR
) 
AS 
BEGIN
    OPEN TIPOFILTROCURSOR FOR
    SELECT JSON_OBJECT(
        'id' VALUE id,
        'criterio' VALUE criterio
    ) FROM ADMIN.TIPO_FILTRO
    WHERE id = FILTRO_ID;
END TIPO_FILTRO_ITEM_ID;